"""Obsidian integration for exporting news items as markdown notes."""

from pathlib import Path
from datetime import datetime
from typing import List
import yaml

from src.models import NewsItem
from src.config import Config


class ObsidianWriter:
    """Writes news items to Obsidian vault as markdown files."""
    
    def __init__(self, config: Config):
        self.config = config
        self.vault_path = config.get_obsidian_vault_path()
        self.base_folder = config.get('obsidian.base_folder', 'AI-News')
    
    def export_scanned_items(self, items: List[NewsItem]):
        """Export all scanned items to Obsidian."""
        print(f"📝 Exporting {len(items)} items to Obsidian...")
        
        for item in items:
            self._write_scanned_note(item)
        
        print(f"✅ Exported to {self.vault_path / self.base_folder}")
    
    def export_deep_dive(self, item: NewsItem):
        """Export a deep dive item (update existing note)."""
        print(f"📝 Exporting deep dive: {item.title[:50]}...")
        self._write_deep_dive_note(item)
    
    def _get_week_folder(self, week: str) -> Path:
        """Get the folder path for a specific week."""
        folder = self.vault_path / self.base_folder / week
        folder.mkdir(parents=True, exist_ok=True)
        return folder
    
    def _sanitize_filename(self, title: str) -> str:
        """Create a safe filename from title."""
        # Remove invalid characters
        safe = "".join(c for c in title if c.isalnum() or c in (' ', '-', '_'))
        # Limit length
        safe = safe[:80].strip()
        # Replace spaces with hyphens
        safe = safe.replace(' ', '-')
        return safe.lower()
    
    def _write_scanned_note(self, item: NewsItem):
        """Write a scanned item note to Obsidian."""
        week_folder = self._get_week_folder(item.week)
        filename = self._sanitize_filename(item.title) + '.md'
        filepath = week_folder / filename
        
        # YAML frontmatter
        frontmatter = {
            'title': item.title,
            'source': item.source,
            'url': item.url,
            'discovered': item.discovered.isoformat(),
            'status': 'scanned',
            'score': round(item.score, 1),
            'tags': item.tags,
            'week': item.week
        }
        
        # Build markdown content
        content = f"""---
{yaml.dump(frontmatter, default_flow_style=False, allow_unicode=True)}---

# {item.title}

**Source:** [{item.source}]({item.url})
**Date:** {item.discovered.strftime('%Y-%m-%d')}
**Status:** 🔍 Scanned
**Score:** {item.score:.1f}/100

## Summary

{item.summary or 'No summary available.'}

## Tags

{', '.join(item.tags) if item.tags else 'No tags generated.'}

---
*Auto-generated by AI News Aggregator*
"""
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
    
    def _write_deep_dive_note(self, item: NewsItem):
        """Write/update a deep dive note to Obsidian."""
        week_folder = self._get_week_folder(item.week)
        filename = self._sanitize_filename(item.title) + '.md'
        filepath = week_folder / filename
        
        # YAML frontmatter
        frontmatter = {
            'title': item.title,
            'source': item.source,
            'url': item.url,
            'discovered': item.discovered.isoformat(),
            'status': 'deep-dive',
            'score': round(item.score, 1),
            'tags': item.tags,
            'week': item.week,
            'slide_file': item.slide_file,
            'slide_number': item.slide_number
        }
        
        related = self._format_related_sources(item)
        slide_ref = f"Presentation: `{item.slide_file}`  \nSlide: {item.slide_number}" if item.slide_file else ""

        # Build markdown content
        content = f"""---
{yaml.dump(frontmatter, default_flow_style=False, allow_unicode=True)}---

# {item.title}

**Source:** [{item.source}]({item.url})
**Date:** {item.discovered.strftime('%Y-%m-%d')}
**Status:** 🔬 Deep Dive
**Score:** {item.score:.1f}/100

## Summary

{item.summary or 'No summary available.'}

## The Story

{item.narrative or 'Narrative not yet generated.'}

## Tags

{', '.join(item.tags) if item.tags else 'No tags generated.'}
"""

        if related:
            content += f"\n## Related Sources\n\n{related}\n"

        if slide_ref:
            content += f"\n## Slide Reference\n\n{slide_ref}\n"

        content += f"\n---\n*Deep dive completed: {datetime.now().strftime('%Y-%m-%d %H:%M')}*\n"
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
    
    def _format_related_sources(self, item: NewsItem) -> str:
        """Format related sources."""
        if not item.research_sources:
            return "No additional sources yet."
        
        formatted = []
        for i, source in enumerate(item.research_sources, 1):
            formatted.append(f"{i}. [Source {i}]({source})")
        
        return '\n'.join(formatted)
